# Generated by Django 2.2.13 on 2020-06-10 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_auto_20200610_0707"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customtext", old_name="hgfjhgfhgf", new_name="hgfhjgf",
        ),
        migrations.RenameField(
            model_name="customtext", old_name="mhgfkhgfkh", new_name="jhgjhgk",
        ),
        migrations.RemoveField(model_name="customtext", name="ghfkjfjf",),
        migrations.RemoveField(model_name="customtext", name="hgfkhfkhf",),
        migrations.RemoveField(model_name="customtext", name="kjhlkjhkljh",),
        migrations.RemoveField(model_name="customtext", name="sgdagdasd",),
        migrations.RemoveField(model_name="customtext", name="ytgfhgfkhgf",),
        migrations.AddField(
            model_name="customtext",
            name="gfhgfjhfjhgf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_gfhgfjhfjhgf",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hfkhgfhgf",
            field=models.ManyToManyField(
                blank=True, related_name="customtext_hfkhgfhgf", to="home.HomePage"
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hgfhgfkh",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_hgfhgfkh",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jhgkhgljhg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="nvhgjfghfg",
            field=models.ManyToManyField(
                blank=True, related_name="customtext_nvhgjfghfg", to="home.HomePage"
            ),
        ),
    ]
