# Generated by Django 2.2.13 on 2020-06-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200610_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='gfhgfjhfjhgf',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hfkhgfhgf',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hgfhgfkh',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hgfhjgf',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjhgk',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgkhgljhg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='nvhgjfghfg',
        ),
    ]
