# Generated by Django 2.2.13 on 2020-06-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_auto_20200610_0724"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="adsdfa",),
        migrations.RemoveField(model_name="customtext", name="asaw",),
        migrations.RemoveField(model_name="customtext", name="gfjhgfjgf",),
        migrations.RemoveField(model_name="customtext", name="gfkhgfjghf",),
        migrations.RemoveField(model_name="customtext", name="sfef",),
    ]
