# Generated by Django 2.2.13 on 2020-06-10 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20200610_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='HUtg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsgwegfsd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hutg_fsgwegfsd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
