# Generated by Django 2.2.13 on 2020-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hutg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hutg',
            name='fsgwegfsd',
        ),
        migrations.AddField(
            model_name='hutg',
            name='swsd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
