# Generated by Django 2.2.13 on 2020-06-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200610_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hutg',
            old_name='swsd',
            new_name='fwer',
        ),
    ]
